/// Flutter icons BanklinIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BanklinIcons
///      fonts:
///       - asset: fonts/BanklinIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BanklinIcons {
  BanklinIcons._();

  static const _kFontFam = 'BanklinIcons';
  static const _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signs = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cc_amex = IconData(0xf1f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
